# Generated by Django 5.0.7 on 2024-07-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultOfQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Student Name')),
                ('correct', models.CharField(max_length=30)),
                ('wrong', models.CharField(max_length=15)),
                ('emty', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('poor', 'poor'), ('medium', 'medium'), ('normal', 'normal'), ('good', 'good'), ('perfect', 'perfect')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
